/*
 * This is part of ElimTSP, a set of codes for eliminating edges in the
 * (symmetric) traveling salesman problem. The codes are based on the
 * paper "Local elimination in the traveling salesman problem" by William Cook,
 * Keld Helsgaun, Stefan Hougardy, and Rasmus T. Schroeder.
 */

/*
MIT License

Copyright (c) 2023  William Cook

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/


/****************************************************************************/
/*                                                                          */
/*  Written by:  Cook, 2013                                                 */
/*  Last Update: May 24, 2016                                               */
/*                                                                          */
/*  Exported Functions                                                      */
/*                                                                          */
/*  void CCelim_compare_three_swap (int a, int b, int c, int d, int e,      */
/*      int f, int **M, int *good, int *I)                                  */
/*    RECONNECT tour after deleting edges a-b, c-d, e-f; these 6 nodes      */
/*      must be in the order they appear in the tour                        */
/*     -M is the distance matrix for the TSP                                */
/*     -good is set to 1 if we find an improving swap                       */
/*     -I lists the edges to reconnect the tour (as a 6-node array)         */
/*                                                                          */
/*  void CCelim_compare_four_swap (int a, int b, int c, int d, int e,       */
/*      int f, int g, int h, int **M, int *good, int *I)                    */
/*                                                                          */
/*  void CClelim_compare_five_swap (int a, int b, int c, int d, int e,      */
/*      int f, int g, int h, int i, int j, int **M, int *good, int *I)      */
/*                                                                          */
/****************************************************************************/

#include <stdio.h>
#include "ccutil.h"
#include "elim.h"

/* The following functions examine ways to reconnect a tour after  */
/* deleting 3, 4, or 5 edges. The code was generated by genswap.c  */

void CCelim_compare_three_swap (int a, int b, int c, int d, int e, int f,
        int **M, int *good, int *I)
{
    int r;

    *good = 1;

    /* Delete a-b c-d e-f */

    r = M[a][b] + M[c][d] + M[e][f];

    /* Case 1: Add c-e d-a f-b for tour Abc */
    if (M[c][e] + M[d][a] + M[f][b] < r) {
        I[0]=c; I[1]=e; I[2]=d; I[3]=a; I[4]=f; I[5]=b;
        return;
    }

    /* Case 2: Add c-f a-d e-b for tour ACB */
    if (M[c][f] + M[a][d] + M[e][b] < r) {
        I[0]=c; I[1]=f; I[2]=a; I[3]=d; I[4]=e; I[5]=b;
        return;
    }

    /* Case 3: Add c-f a-e d-b for tour ACb */
    if (M[c][f] + M[a][e] + M[d][b] < r) {
        I[0]=c; I[1]=f; I[2]=a; I[3]=e; I[4]=d; I[5]=b;
        return;
    }

    /* Case 4: Add c-a f-d e-b for tour AcB */
    if (M[c][a] + M[f][d] + M[e][b] < r) {
        I[0]=c; I[1]=a; I[2]=f; I[3]=d; I[4]=e; I[5]=b;
        return;
    }

    *good = 0;
}

void CCelim_compare_four_swap (int a, int b, int c, int d, int e, int f,
        int g, int h, int **M, int *good, int *I)
{
    int r;

    *good = 1;

    /* Delete a-b c-d e-f g-h */

    r = M[a][b] + M[c][d] + M[e][f] + M[g][h];

    /* Case 1: Add c-e d-f g-a h-b for tour AbCd */
    if (M[c][e] + M[d][f] + M[g][a] + M[h][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=f;
       I[4]=g; I[5]=a; I[6]=h; I[7]=b;
       return;
    }

    /* Case 2: Add c-e d-g f-a h-b for tour Abcd */
    if (M[c][e] + M[d][g] + M[f][a] + M[h][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=g;
       I[4]=f; I[5]=a; I[6]=h; I[7]=b;
       return;
    }

    /* Case 3: Add c-e d-h a-f g-b for tour AbDC */
    if (M[c][e] + M[d][h] + M[a][f] + M[g][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=h;
       I[4]=a; I[5]=f; I[6]=g; I[7]=b;
       return;
    }

    /* Case 4: Add c-e d-h a-g f-b for tour AbDc */
    if (M[c][e] + M[d][h] + M[a][g] + M[f][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=h;
       I[4]=a; I[5]=g; I[6]=f; I[7]=b;
       return;
    }

    /* Case 5: Add c-e d-a h-f g-b for tour AbdC */
    if (M[c][e] + M[d][a] + M[h][f] + M[g][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=a;
       I[4]=h; I[5]=f; I[6]=g; I[7]=b;
       return;
    }

    /* Case 6: Add c-f g-d e-a h-b for tour ACBd */
    if (M[c][f] + M[g][d] + M[e][a] + M[h][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=d;
       I[4]=e; I[5]=a; I[6]=h; I[7]=b;
       return;
    }

    /* Case 7: Add c-f g-e d-a h-b for tour ACbd */
    if (M[c][f] + M[g][e] + M[d][a] + M[h][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=e;
       I[4]=d; I[5]=a; I[6]=h; I[7]=b;
       return;
    }

    /* Case 8: Add c-g f-d e-a h-b for tour AcBd */
    if (M[c][g] + M[f][d] + M[e][a] + M[h][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=d;
       I[4]=e; I[5]=a; I[6]=h; I[7]=b;
       return;
    }

    /* Case 9: Add c-f g-a h-d e-b for tour ACdB */
    if (M[c][f] + M[g][a] + M[h][d] + M[e][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=a;
       I[4]=h; I[5]=d; I[6]=e; I[7]=b;
       return;
    }

    /* Case 10: Add c-f g-a h-e d-b for tour ACdb */
    if (M[c][f] + M[g][a] + M[h][e] + M[d][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=a;
       I[4]=h; I[5]=e; I[6]=d; I[7]=b;
       return;
    }

    /* Case 11: Add c-g f-h a-d e-b for tour AcDB */
    if (M[c][g] + M[f][h] + M[a][d] + M[e][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=h;
       I[4]=a; I[5]=d; I[6]=e; I[7]=b;
       return;
    }

    /* Case 12: Add c-g f-h a-e d-b for tour AcDb */
    if (M[c][g] + M[f][h] + M[a][e] + M[d][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=h;
       I[4]=a; I[5]=e; I[6]=d; I[7]=b;
       return;
    }

    /* Case 13: Add c-g f-a h-d e-b for tour AcdB */
    if (M[c][g] + M[f][a] + M[h][d] + M[e][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=a;
       I[4]=h; I[5]=d; I[6]=e; I[7]=b;
       return;
    }

    /* Case 14: Add c-g f-a h-e d-b for tour Acdb */
    if (M[c][g] + M[f][a] + M[h][e] + M[d][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=a;
       I[4]=h; I[5]=e; I[6]=d; I[7]=b;
       return;
    }

    /* Case 15: Add c-h a-f g-d e-b for tour ADCB */
    if (M[c][h] + M[a][f] + M[g][d] + M[e][b] < r) {
       I[0]=c; I[1]=h; I[2]=a; I[3]=f;
       I[4]=g; I[5]=d; I[6]=e; I[7]=b;
       return;
    }

    /* Case 16: Add c-h a-f g-e d-b for tour ADCb */
    if (M[c][h] + M[a][f] + M[g][e] + M[d][b] < r) {
       I[0]=c; I[1]=h; I[2]=a; I[3]=f;
       I[4]=g; I[5]=e; I[6]=d; I[7]=b;
       return;
    }

    /* Case 17: Add c-h a-g f-d e-b for tour ADcB */
    if (M[c][h] + M[a][g] + M[f][d] + M[e][b] < r) {
       I[0]=c; I[1]=h; I[2]=a; I[3]=g;
       I[4]=f; I[5]=d; I[6]=e; I[7]=b;
       return;
    }

    /* Case 18: Add c-a h-f g-d e-b for tour AdCB */
    if (M[c][a] + M[h][f] + M[g][d] + M[e][b] < r) {
       I[0]=c; I[1]=a; I[2]=h; I[3]=f;
       I[4]=g; I[5]=d; I[6]=e; I[7]=b;
       return;
    }

    /* Case 19: Add c-a h-f g-e d-b for tour AdCb */
    if (M[c][a] + M[h][f] + M[g][e] + M[d][b] < r) {
       I[0]=c; I[1]=a; I[2]=h; I[3]=f;
       I[4]=g; I[5]=e; I[6]=d; I[7]=b;
       return;
    }

    /* Case 20: Add c-h a-d e-g f-b for tour ADBc */
    if (M[c][h] + M[a][d] + M[e][g] + M[f][b] < r) {
       I[0]=c; I[1]=h; I[2]=a; I[3]=d;
       I[4]=e; I[5]=g; I[6]=f; I[7]=b;
       return;
    }

    /* Case 21: Add c-h a-e d-f g-b for tour ADbC */
    if (M[c][h] + M[a][e] + M[d][f] + M[g][b] < r) {
       I[0]=c; I[1]=h; I[2]=a; I[3]=e;
       I[4]=d; I[5]=f; I[6]=g; I[7]=b;
       return;
    }

    /* Case 22: Add c-h a-e d-g f-b for tour ADbc */
    if (M[c][h] + M[a][e] + M[d][g] + M[f][b] < r) {
       I[0]=c; I[1]=h; I[2]=a; I[3]=e;
       I[4]=d; I[5]=g; I[6]=f; I[7]=b;
       return;
    }

    /* Case 23: Add c-a h-d e-g f-b for tour AdBc */
    if (M[c][a] + M[h][d] + M[e][g] + M[f][b] < r) {
       I[0]=c; I[1]=a; I[2]=h; I[3]=d;
       I[4]=e; I[5]=g; I[6]=f; I[7]=b;
       return;
    }

    /* Case 24: Add c-a h-e d-f g-b for tour AdbC */
    if (M[c][a] + M[h][e] + M[d][f] + M[g][b] < r) {
       I[0]=c; I[1]=a; I[2]=h; I[3]=e;
       I[4]=d; I[5]=f; I[6]=g; I[7]=b;
       return;
    }

    /* Case 25: Add c-a h-e d-g f-b for tour Adbc */
    if (M[c][a] + M[h][e] + M[d][g] + M[f][b] < r) {
       I[0]=c; I[1]=a; I[2]=h; I[3]=e;
       I[4]=d; I[5]=g; I[6]=f; I[7]=b;
       return;
    }

    *good = 0;
}

void CCelim_compare_five_swap (int a, int b, int c, int d, int e, int f, int g,
        int h, int i, int j, int **M, int *good, int *I)
{
    int r;

    *good = 1;

    /* Delete a-b c-d e-f g-h i-j */

    r = M[a][b] + M[c][d] + M[e][f] + M[g][h] + M[i][j];

    /* Case 1: Add c-e d-f g-i h-a j-b for tour AbCde */
    if (M[c][e] + M[d][f] + M[g][i] + M[h][a] + M[j][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=f;
       I[4]=g; I[5]=i; I[6]=h; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 2: Add c-e d-g f-h i-a j-b for tour AbcDe */
    if (M[c][e] + M[d][g] + M[f][h] + M[i][a] + M[j][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=g;
       I[4]=f; I[5]=h; I[6]=i; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 3: Add c-e d-g f-i h-a j-b for tour Abcde */
    if (M[c][e] + M[d][g] + M[f][i] + M[h][a] + M[j][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=g;
       I[4]=f; I[5]=i; I[6]=h; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 4: Add c-e d-f g-j a-h i-b for tour AbCED */
    if (M[c][e] + M[d][f] + M[g][j] + M[a][h] + M[i][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=f;
       I[4]=g; I[5]=j; I[6]=a; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 5: Add c-e d-f g-j a-i h-b for tour AbCEd */
    if (M[c][e] + M[d][f] + M[g][j] + M[a][i] + M[h][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=f;
       I[4]=g; I[5]=j; I[6]=a; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 6: Add c-e d-f g-a j-h i-b for tour AbCeD */
    if (M[c][e] + M[d][f] + M[g][a] + M[j][h] + M[i][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=f;
       I[4]=g; I[5]=a; I[6]=j; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 7: Add c-e d-g f-j a-h i-b for tour AbcED */
    if (M[c][e] + M[d][g] + M[f][j] + M[a][h] + M[i][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=g;
       I[4]=f; I[5]=j; I[6]=a; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 8: Add c-e d-g f-j a-i h-b for tour AbcEd */
    if (M[c][e] + M[d][g] + M[f][j] + M[a][i] + M[h][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=g;
       I[4]=f; I[5]=j; I[6]=a; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 9: Add c-e d-g f-a j-h i-b for tour AbceD */
    if (M[c][e] + M[d][g] + M[f][a] + M[j][h] + M[i][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=g;
       I[4]=f; I[5]=a; I[6]=j; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 10: Add c-e d-h i-f g-a j-b for tour AbDCe */
    if (M[c][e] + M[d][h] + M[i][f] + M[g][a] + M[j][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=h;
       I[4]=i; I[5]=f; I[6]=g; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 11: Add c-e d-h i-g f-a j-b for tour AbDce */
    if (M[c][e] + M[d][h] + M[i][g] + M[f][a] + M[j][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=h;
       I[4]=i; I[5]=g; I[6]=f; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 12: Add c-e d-i h-f g-a j-b for tour AbdCe */
    if (M[c][e] + M[d][i] + M[h][f] + M[g][a] + M[j][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=i;
       I[4]=h; I[5]=f; I[6]=g; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 13: Add c-e d-h i-a j-f g-b for tour AbDeC */
    if (M[c][e] + M[d][h] + M[i][a] + M[j][f] + M[g][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=h;
       I[4]=i; I[5]=a; I[6]=j; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 14: Add c-e d-h i-a j-g f-b for tour AbDec */
    if (M[c][e] + M[d][h] + M[i][a] + M[j][g] + M[f][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=h;
       I[4]=i; I[5]=a; I[6]=j; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 15: Add c-e d-i h-j a-f g-b for tour AbdEC */
    if (M[c][e] + M[d][i] + M[h][j] + M[a][f] + M[g][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=i;
       I[4]=h; I[5]=j; I[6]=a; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 16: Add c-e d-i h-j a-g f-b for tour AbdEc */
    if (M[c][e] + M[d][i] + M[h][j] + M[a][g] + M[f][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=i;
       I[4]=h; I[5]=j; I[6]=a; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 17: Add c-e d-i h-a j-f g-b for tour AbdeC */
    if (M[c][e] + M[d][i] + M[h][a] + M[j][f] + M[g][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=i;
       I[4]=h; I[5]=a; I[6]=j; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 18: Add c-e d-i h-a j-g f-b for tour Abdec */
    if (M[c][e] + M[d][i] + M[h][a] + M[j][g] + M[f][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=i;
       I[4]=h; I[5]=a; I[6]=j; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 19: Add c-e d-j a-h i-f g-b for tour AbEDC */
    if (M[c][e] + M[d][j] + M[a][h] + M[i][f] + M[g][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=j;
       I[4]=a; I[5]=h; I[6]=i; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 20: Add c-e d-j a-h i-g f-b for tour AbEDc */
    if (M[c][e] + M[d][j] + M[a][h] + M[i][g] + M[f][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=j;
       I[4]=a; I[5]=h; I[6]=i; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 21: Add c-e d-j a-i h-f g-b for tour AbEdC */
    if (M[c][e] + M[d][j] + M[a][i] + M[h][f] + M[g][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=j;
       I[4]=a; I[5]=i; I[6]=h; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 22: Add c-e d-a j-h i-f g-b for tour AbeDC */
    if (M[c][e] + M[d][a] + M[j][h] + M[i][f] + M[g][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=a;
       I[4]=j; I[5]=h; I[6]=i; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 23: Add c-e d-a j-h i-g f-b for tour AbeDc */
    if (M[c][e] + M[d][a] + M[j][h] + M[i][g] + M[f][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=a;
       I[4]=j; I[5]=h; I[6]=i; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 24: Add c-e d-j a-f g-i h-b for tour AbECd */
    if (M[c][e] + M[d][j] + M[a][f] + M[g][i] + M[h][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=j;
       I[4]=a; I[5]=f; I[6]=g; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 25: Add c-e d-j a-g f-h i-b for tour AbEcD */
    if (M[c][e] + M[d][j] + M[a][g] + M[f][h] + M[i][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=j;
       I[4]=a; I[5]=g; I[6]=f; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 26: Add c-e d-j a-g f-i h-b for tour AbEcd */
    if (M[c][e] + M[d][j] + M[a][g] + M[f][i] + M[h][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=j;
       I[4]=a; I[5]=g; I[6]=f; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 27: Add c-e d-a j-f g-i h-b for tour AbeCd */
    if (M[c][e] + M[d][a] + M[j][f] + M[g][i] + M[h][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=a;
       I[4]=j; I[5]=f; I[6]=g; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 28: Add c-e d-a j-g f-h i-b for tour AbecD */
    if (M[c][e] + M[d][a] + M[j][g] + M[f][h] + M[i][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=a;
       I[4]=j; I[5]=g; I[6]=f; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 29: Add c-e d-a j-g f-i h-b for tour Abecd */
    if (M[c][e] + M[d][a] + M[j][g] + M[f][i] + M[h][b] < r) {
       I[0]=c; I[1]=e; I[2]=d; I[3]=a;
       I[4]=j; I[5]=g; I[6]=f; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 30: Add c-f g-d e-h i-a j-b for tour ACBDe */
    if (M[c][f] + M[g][d] + M[e][h] + M[i][a] + M[j][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=d;
       I[4]=e; I[5]=h; I[6]=i; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 31: Add c-f g-d e-i h-a j-b for tour ACBde */
    if (M[c][f] + M[g][d] + M[e][i] + M[h][a] + M[j][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=d;
       I[4]=e; I[5]=i; I[6]=h; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 32: Add c-f g-e d-h i-a j-b for tour ACbDe */
    if (M[c][f] + M[g][e] + M[d][h] + M[i][a] + M[j][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=e;
       I[4]=d; I[5]=h; I[6]=i; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 33: Add c-f g-e d-i h-a j-b for tour ACbde */
    if (M[c][f] + M[g][e] + M[d][i] + M[h][a] + M[j][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=e;
       I[4]=d; I[5]=i; I[6]=h; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 34: Add c-g f-d e-h i-a j-b for tour AcBDe */
    if (M[c][g] + M[f][d] + M[e][h] + M[i][a] + M[j][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=d;
       I[4]=e; I[5]=h; I[6]=i; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 35: Add c-g f-d e-i h-a j-b for tour AcBde */
    if (M[c][g] + M[f][d] + M[e][i] + M[h][a] + M[j][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=d;
       I[4]=e; I[5]=i; I[6]=h; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 36: Add c-f g-d e-j a-h i-b for tour ACBED */
    if (M[c][f] + M[g][d] + M[e][j] + M[a][h] + M[i][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=d;
       I[4]=e; I[5]=j; I[6]=a; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 37: Add c-f g-d e-j a-i h-b for tour ACBEd */
    if (M[c][f] + M[g][d] + M[e][j] + M[a][i] + M[h][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=d;
       I[4]=e; I[5]=j; I[6]=a; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 38: Add c-f g-d e-a j-h i-b for tour ACBeD */
    if (M[c][f] + M[g][d] + M[e][a] + M[j][h] + M[i][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=d;
       I[4]=e; I[5]=a; I[6]=j; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 39: Add c-f g-e d-j a-h i-b for tour ACbED */
    if (M[c][f] + M[g][e] + M[d][j] + M[a][h] + M[i][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=e;
       I[4]=d; I[5]=j; I[6]=a; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 40: Add c-f g-e d-j a-i h-b for tour ACbEd */
    if (M[c][f] + M[g][e] + M[d][j] + M[a][i] + M[h][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=e;
       I[4]=d; I[5]=j; I[6]=a; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 41: Add c-f g-e d-a j-h i-b for tour ACbeD */
    if (M[c][f] + M[g][e] + M[d][a] + M[j][h] + M[i][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=e;
       I[4]=d; I[5]=a; I[6]=j; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 42: Add c-g f-d e-j a-h i-b for tour AcBED */
    if (M[c][g] + M[f][d] + M[e][j] + M[a][h] + M[i][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=d;
       I[4]=e; I[5]=j; I[6]=a; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 43: Add c-g f-d e-j a-i h-b for tour AcBEd */
    if (M[c][g] + M[f][d] + M[e][j] + M[a][i] + M[h][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=d;
       I[4]=e; I[5]=j; I[6]=a; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 44: Add c-g f-d e-a j-h i-b for tour AcBeD */
    if (M[c][g] + M[f][d] + M[e][a] + M[j][h] + M[i][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=d;
       I[4]=e; I[5]=a; I[6]=j; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 45: Add c-f g-i h-d e-a j-b for tour ACdBe */
    if (M[c][f] + M[g][i] + M[h][d] + M[e][a] + M[j][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=i;
       I[4]=h; I[5]=d; I[6]=e; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 46: Add c-f g-i h-e d-a j-b for tour ACdbe */
    if (M[c][f] + M[g][i] + M[h][e] + M[d][a] + M[j][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=i;
       I[4]=h; I[5]=e; I[6]=d; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 47: Add c-g f-h i-d e-a j-b for tour AcDBe */
    if (M[c][g] + M[f][h] + M[i][d] + M[e][a] + M[j][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=h;
       I[4]=i; I[5]=d; I[6]=e; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 48: Add c-g f-h i-e d-a j-b for tour AcDbe */
    if (M[c][g] + M[f][h] + M[i][e] + M[d][a] + M[j][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=h;
       I[4]=i; I[5]=e; I[6]=d; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 49: Add c-g f-i h-d e-a j-b for tour AcdBe */
    if (M[c][g] + M[f][i] + M[h][d] + M[e][a] + M[j][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=i;
       I[4]=h; I[5]=d; I[6]=e; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 50: Add c-g f-i h-e d-a j-b for tour Acdbe */
    if (M[c][g] + M[f][i] + M[h][e] + M[d][a] + M[j][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=i;
       I[4]=h; I[5]=e; I[6]=d; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 51: Add c-f g-i h-j a-d e-b for tour ACdEB */
    if (M[c][f] + M[g][i] + M[h][j] + M[a][d] + M[e][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=i;
       I[4]=h; I[5]=j; I[6]=a; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 52: Add c-f g-i h-j a-e d-b for tour ACdEb */
    if (M[c][f] + M[g][i] + M[h][j] + M[a][e] + M[d][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=i;
       I[4]=h; I[5]=j; I[6]=a; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 53: Add c-f g-i h-a j-d e-b for tour ACdeB */
    if (M[c][f] + M[g][i] + M[h][a] + M[j][d] + M[e][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=i;
       I[4]=h; I[5]=a; I[6]=j; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 54: Add c-f g-i h-a j-e d-b for tour ACdeb */
    if (M[c][f] + M[g][i] + M[h][a] + M[j][e] + M[d][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=i;
       I[4]=h; I[5]=a; I[6]=j; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 55: Add c-g f-h i-a j-d e-b for tour AcDeB */
    if (M[c][g] + M[f][h] + M[i][a] + M[j][d] + M[e][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=h;
       I[4]=i; I[5]=a; I[6]=j; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 56: Add c-g f-h i-a j-e d-b for tour AcDeb */
    if (M[c][g] + M[f][h] + M[i][a] + M[j][e] + M[d][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=h;
       I[4]=i; I[5]=a; I[6]=j; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 57: Add c-g f-i h-j a-d e-b for tour AcdEB */
    if (M[c][g] + M[f][i] + M[h][j] + M[a][d] + M[e][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=i;
       I[4]=h; I[5]=j; I[6]=a; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 58: Add c-g f-i h-j a-e d-b for tour AcdEb */
    if (M[c][g] + M[f][i] + M[h][j] + M[a][e] + M[d][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=i;
       I[4]=h; I[5]=j; I[6]=a; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 59: Add c-g f-i h-a j-d e-b for tour AcdeB */
    if (M[c][g] + M[f][i] + M[h][a] + M[j][d] + M[e][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=i;
       I[4]=h; I[5]=a; I[6]=j; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 60: Add c-g f-i h-a j-e d-b for tour Acdeb */
    if (M[c][g] + M[f][i] + M[h][a] + M[j][e] + M[d][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=i;
       I[4]=h; I[5]=a; I[6]=j; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 61: Add c-f g-j a-h i-d e-b for tour ACEDB */
    if (M[c][f] + M[g][j] + M[a][h] + M[i][d] + M[e][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=j;
       I[4]=a; I[5]=h; I[6]=i; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 62: Add c-f g-j a-h i-e d-b for tour ACEDb */
    if (M[c][f] + M[g][j] + M[a][h] + M[i][e] + M[d][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=j;
       I[4]=a; I[5]=h; I[6]=i; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 63: Add c-f g-j a-i h-d e-b for tour ACEdB */
    if (M[c][f] + M[g][j] + M[a][i] + M[h][d] + M[e][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=j;
       I[4]=a; I[5]=i; I[6]=h; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 64: Add c-f g-j a-i h-e d-b for tour ACEdb */
    if (M[c][f] + M[g][j] + M[a][i] + M[h][e] + M[d][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=j;
       I[4]=a; I[5]=i; I[6]=h; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 65: Add c-f g-a j-h i-d e-b for tour ACeDB */
    if (M[c][f] + M[g][a] + M[j][h] + M[i][d] + M[e][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=a;
       I[4]=j; I[5]=h; I[6]=i; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 66: Add c-f g-a j-h i-e d-b for tour ACeDb */
    if (M[c][f] + M[g][a] + M[j][h] + M[i][e] + M[d][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=a;
       I[4]=j; I[5]=h; I[6]=i; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 67: Add c-g f-j a-h i-d e-b for tour AcEDB */
    if (M[c][g] + M[f][j] + M[a][h] + M[i][d] + M[e][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=j;
       I[4]=a; I[5]=h; I[6]=i; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 68: Add c-g f-j a-h i-e d-b for tour AcEDb */
    if (M[c][g] + M[f][j] + M[a][h] + M[i][e] + M[d][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=j;
       I[4]=a; I[5]=h; I[6]=i; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 69: Add c-g f-j a-i h-d e-b for tour AcEdB */
    if (M[c][g] + M[f][j] + M[a][i] + M[h][d] + M[e][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=j;
       I[4]=a; I[5]=i; I[6]=h; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 70: Add c-g f-j a-i h-e d-b for tour AcEdb */
    if (M[c][g] + M[f][j] + M[a][i] + M[h][e] + M[d][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=j;
       I[4]=a; I[5]=i; I[6]=h; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 71: Add c-g f-a j-h i-d e-b for tour AceDB */
    if (M[c][g] + M[f][a] + M[j][h] + M[i][d] + M[e][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=a;
       I[4]=j; I[5]=h; I[6]=i; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 72: Add c-g f-a j-h i-e d-b for tour AceDb */
    if (M[c][g] + M[f][a] + M[j][h] + M[i][e] + M[d][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=a;
       I[4]=j; I[5]=h; I[6]=i; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 73: Add c-f g-j a-d e-h i-b for tour ACEBD */
    if (M[c][f] + M[g][j] + M[a][d] + M[e][h] + M[i][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=j;
       I[4]=a; I[5]=d; I[6]=e; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 74: Add c-f g-j a-d e-i h-b for tour ACEBd */
    if (M[c][f] + M[g][j] + M[a][d] + M[e][i] + M[h][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=j;
       I[4]=a; I[5]=d; I[6]=e; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 75: Add c-f g-j a-e d-h i-b for tour ACEbD */
    if (M[c][f] + M[g][j] + M[a][e] + M[d][h] + M[i][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=j;
       I[4]=a; I[5]=e; I[6]=d; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 76: Add c-f g-j a-e d-i h-b for tour ACEbd */
    if (M[c][f] + M[g][j] + M[a][e] + M[d][i] + M[h][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=j;
       I[4]=a; I[5]=e; I[6]=d; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 77: Add c-f g-a j-d e-h i-b for tour ACeBD */
    if (M[c][f] + M[g][a] + M[j][d] + M[e][h] + M[i][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=a;
       I[4]=j; I[5]=d; I[6]=e; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 78: Add c-f g-a j-d e-i h-b for tour ACeBd */
    if (M[c][f] + M[g][a] + M[j][d] + M[e][i] + M[h][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=a;
       I[4]=j; I[5]=d; I[6]=e; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 79: Add c-f g-a j-e d-h i-b for tour ACebD */
    if (M[c][f] + M[g][a] + M[j][e] + M[d][h] + M[i][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=a;
       I[4]=j; I[5]=e; I[6]=d; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 80: Add c-f g-a j-e d-i h-b for tour ACebd */
    if (M[c][f] + M[g][a] + M[j][e] + M[d][i] + M[h][b] < r) {
       I[0]=c; I[1]=f; I[2]=g; I[3]=a;
       I[4]=j; I[5]=e; I[6]=d; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 81: Add c-g f-j a-d e-h i-b for tour AcEBD */
    if (M[c][g] + M[f][j] + M[a][d] + M[e][h] + M[i][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=j;
       I[4]=a; I[5]=d; I[6]=e; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 82: Add c-g f-j a-d e-i h-b for tour AcEBd */
    if (M[c][g] + M[f][j] + M[a][d] + M[e][i] + M[h][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=j;
       I[4]=a; I[5]=d; I[6]=e; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 83: Add c-g f-j a-e d-h i-b for tour AcEbD */
    if (M[c][g] + M[f][j] + M[a][e] + M[d][h] + M[i][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=j;
       I[4]=a; I[5]=e; I[6]=d; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 84: Add c-g f-j a-e d-i h-b for tour AcEbd */
    if (M[c][g] + M[f][j] + M[a][e] + M[d][i] + M[h][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=j;
       I[4]=a; I[5]=e; I[6]=d; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 85: Add c-g f-a j-d e-h i-b for tour AceBD */
    if (M[c][g] + M[f][a] + M[j][d] + M[e][h] + M[i][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=a;
       I[4]=j; I[5]=d; I[6]=e; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 86: Add c-g f-a j-d e-i h-b for tour AceBd */
    if (M[c][g] + M[f][a] + M[j][d] + M[e][i] + M[h][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=a;
       I[4]=j; I[5]=d; I[6]=e; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 87: Add c-g f-a j-e d-h i-b for tour AcebD */
    if (M[c][g] + M[f][a] + M[j][e] + M[d][h] + M[i][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=a;
       I[4]=j; I[5]=e; I[6]=d; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 88: Add c-g f-a j-e d-i h-b for tour Acebd */
    if (M[c][g] + M[f][a] + M[j][e] + M[d][i] + M[h][b] < r) {
       I[0]=c; I[1]=g; I[2]=f; I[3]=a;
       I[4]=j; I[5]=e; I[6]=d; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 89: Add c-h i-f g-d e-a j-b for tour ADCBe */
    if (M[c][h] + M[i][f] + M[g][d] + M[e][a] + M[j][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=f;
       I[4]=g; I[5]=d; I[6]=e; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 90: Add c-h i-f g-e d-a j-b for tour ADCbe */
    if (M[c][h] + M[i][f] + M[g][e] + M[d][a] + M[j][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=f;
       I[4]=g; I[5]=e; I[6]=d; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 91: Add c-h i-g f-d e-a j-b for tour ADcBe */
    if (M[c][h] + M[i][g] + M[f][d] + M[e][a] + M[j][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=g;
       I[4]=f; I[5]=d; I[6]=e; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 92: Add c-i h-f g-d e-a j-b for tour AdCBe */
    if (M[c][i] + M[h][f] + M[g][d] + M[e][a] + M[j][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=f;
       I[4]=g; I[5]=d; I[6]=e; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 93: Add c-i h-f g-e d-a j-b for tour AdCbe */
    if (M[c][i] + M[h][f] + M[g][e] + M[d][a] + M[j][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=f;
       I[4]=g; I[5]=e; I[6]=d; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 94: Add c-h i-f g-j a-d e-b for tour ADCEB */
    if (M[c][h] + M[i][f] + M[g][j] + M[a][d] + M[e][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=f;
       I[4]=g; I[5]=j; I[6]=a; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 95: Add c-h i-f g-j a-e d-b for tour ADCEb */
    if (M[c][h] + M[i][f] + M[g][j] + M[a][e] + M[d][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=f;
       I[4]=g; I[5]=j; I[6]=a; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 96: Add c-h i-f g-a j-d e-b for tour ADCeB */
    if (M[c][h] + M[i][f] + M[g][a] + M[j][d] + M[e][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=f;
       I[4]=g; I[5]=a; I[6]=j; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 97: Add c-h i-f g-a j-e d-b for tour ADCeb */
    if (M[c][h] + M[i][f] + M[g][a] + M[j][e] + M[d][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=f;
       I[4]=g; I[5]=a; I[6]=j; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 98: Add c-h i-g f-j a-d e-b for tour ADcEB */
    if (M[c][h] + M[i][g] + M[f][j] + M[a][d] + M[e][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=g;
       I[4]=f; I[5]=j; I[6]=a; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 99: Add c-h i-g f-j a-e d-b for tour ADcEb */
    if (M[c][h] + M[i][g] + M[f][j] + M[a][e] + M[d][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=g;
       I[4]=f; I[5]=j; I[6]=a; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 100: Add c-h i-g f-a j-d e-b for tour ADceB */
    if (M[c][h] + M[i][g] + M[f][a] + M[j][d] + M[e][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=g;
       I[4]=f; I[5]=a; I[6]=j; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 101: Add c-h i-g f-a j-e d-b for tour ADceb */
    if (M[c][h] + M[i][g] + M[f][a] + M[j][e] + M[d][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=g;
       I[4]=f; I[5]=a; I[6]=j; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 102: Add c-i h-f g-j a-d e-b for tour AdCEB */
    if (M[c][i] + M[h][f] + M[g][j] + M[a][d] + M[e][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=f;
       I[4]=g; I[5]=j; I[6]=a; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 103: Add c-i h-f g-j a-e d-b for tour AdCEb */
    if (M[c][i] + M[h][f] + M[g][j] + M[a][e] + M[d][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=f;
       I[4]=g; I[5]=j; I[6]=a; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 104: Add c-i h-f g-a j-d e-b for tour AdCeB */
    if (M[c][i] + M[h][f] + M[g][a] + M[j][d] + M[e][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=f;
       I[4]=g; I[5]=a; I[6]=j; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 105: Add c-i h-f g-a j-e d-b for tour AdCeb */
    if (M[c][i] + M[h][f] + M[g][a] + M[j][e] + M[d][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=f;
       I[4]=g; I[5]=a; I[6]=j; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 106: Add c-h i-d e-g f-a j-b for tour ADBce */
    if (M[c][h] + M[i][d] + M[e][g] + M[f][a] + M[j][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=d;
       I[4]=e; I[5]=g; I[6]=f; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 107: Add c-h i-e d-f g-a j-b for tour ADbCe */
    if (M[c][h] + M[i][e] + M[d][f] + M[g][a] + M[j][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=e;
       I[4]=d; I[5]=f; I[6]=g; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 108: Add c-h i-e d-g f-a j-b for tour ADbce */
    if (M[c][h] + M[i][e] + M[d][g] + M[f][a] + M[j][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=e;
       I[4]=d; I[5]=g; I[6]=f; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 109: Add c-i h-d e-g f-a j-b for tour AdBce */
    if (M[c][i] + M[h][d] + M[e][g] + M[f][a] + M[j][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=d;
       I[4]=e; I[5]=g; I[6]=f; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 110: Add c-i h-e d-f g-a j-b for tour AdbCe */
    if (M[c][i] + M[h][e] + M[d][f] + M[g][a] + M[j][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=e;
       I[4]=d; I[5]=f; I[6]=g; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 111: Add c-i h-e d-g f-a j-b for tour Adbce */
    if (M[c][i] + M[h][e] + M[d][g] + M[f][a] + M[j][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=e;
       I[4]=d; I[5]=g; I[6]=f; I[7]=a;
       I[8]=j; I[9]=b;
       return;
    }

    /* Case 112: Add c-h i-d e-j a-f g-b for tour ADBEC */
    if (M[c][h] + M[i][d] + M[e][j] + M[a][f] + M[g][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=d;
       I[4]=e; I[5]=j; I[6]=a; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 113: Add c-h i-d e-j a-g f-b for tour ADBEc */
    if (M[c][h] + M[i][d] + M[e][j] + M[a][g] + M[f][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=d;
       I[4]=e; I[5]=j; I[6]=a; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 114: Add c-h i-d e-a j-f g-b for tour ADBeC */
    if (M[c][h] + M[i][d] + M[e][a] + M[j][f] + M[g][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=d;
       I[4]=e; I[5]=a; I[6]=j; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 115: Add c-h i-d e-a j-g f-b for tour ADBec */
    if (M[c][h] + M[i][d] + M[e][a] + M[j][g] + M[f][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=d;
       I[4]=e; I[5]=a; I[6]=j; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 116: Add c-h i-e d-j a-f g-b for tour ADbEC */
    if (M[c][h] + M[i][e] + M[d][j] + M[a][f] + M[g][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=e;
       I[4]=d; I[5]=j; I[6]=a; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 117: Add c-h i-e d-j a-g f-b for tour ADbEc */
    if (M[c][h] + M[i][e] + M[d][j] + M[a][g] + M[f][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=e;
       I[4]=d; I[5]=j; I[6]=a; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 118: Add c-h i-e d-a j-f g-b for tour ADbeC */
    if (M[c][h] + M[i][e] + M[d][a] + M[j][f] + M[g][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=e;
       I[4]=d; I[5]=a; I[6]=j; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 119: Add c-h i-e d-a j-g f-b for tour ADbec */
    if (M[c][h] + M[i][e] + M[d][a] + M[j][g] + M[f][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=e;
       I[4]=d; I[5]=a; I[6]=j; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 120: Add c-i h-d e-j a-f g-b for tour AdBEC */
    if (M[c][i] + M[h][d] + M[e][j] + M[a][f] + M[g][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=d;
       I[4]=e; I[5]=j; I[6]=a; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 121: Add c-i h-d e-j a-g f-b for tour AdBEc */
    if (M[c][i] + M[h][d] + M[e][j] + M[a][g] + M[f][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=d;
       I[4]=e; I[5]=j; I[6]=a; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 122: Add c-i h-d e-a j-f g-b for tour AdBeC */
    if (M[c][i] + M[h][d] + M[e][a] + M[j][f] + M[g][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=d;
       I[4]=e; I[5]=a; I[6]=j; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 123: Add c-i h-d e-a j-g f-b for tour AdBec */
    if (M[c][i] + M[h][d] + M[e][a] + M[j][g] + M[f][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=d;
       I[4]=e; I[5]=a; I[6]=j; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 124: Add c-i h-e d-j a-f g-b for tour AdbEC */
    if (M[c][i] + M[h][e] + M[d][j] + M[a][f] + M[g][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=e;
       I[4]=d; I[5]=j; I[6]=a; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 125: Add c-i h-e d-j a-g f-b for tour AdbEc */
    if (M[c][i] + M[h][e] + M[d][j] + M[a][g] + M[f][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=e;
       I[4]=d; I[5]=j; I[6]=a; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 126: Add c-i h-e d-a j-f g-b for tour AdbeC */
    if (M[c][i] + M[h][e] + M[d][a] + M[j][f] + M[g][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=e;
       I[4]=d; I[5]=a; I[6]=j; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 127: Add c-i h-e d-a j-g f-b for tour Adbec */
    if (M[c][i] + M[h][e] + M[d][a] + M[j][g] + M[f][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=e;
       I[4]=d; I[5]=a; I[6]=j; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 128: Add c-h i-a j-d e-g f-b for tour ADeBc */
    if (M[c][h] + M[i][a] + M[j][d] + M[e][g] + M[f][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=a;
       I[4]=j; I[5]=d; I[6]=e; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 129: Add c-h i-a j-e d-f g-b for tour ADebC */
    if (M[c][h] + M[i][a] + M[j][e] + M[d][f] + M[g][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=a;
       I[4]=j; I[5]=e; I[6]=d; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 130: Add c-h i-a j-e d-g f-b for tour ADebc */
    if (M[c][h] + M[i][a] + M[j][e] + M[d][g] + M[f][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=a;
       I[4]=j; I[5]=e; I[6]=d; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 131: Add c-i h-j a-d e-g f-b for tour AdEBc */
    if (M[c][i] + M[h][j] + M[a][d] + M[e][g] + M[f][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=j;
       I[4]=a; I[5]=d; I[6]=e; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 132: Add c-i h-j a-e d-f g-b for tour AdEbC */
    if (M[c][i] + M[h][j] + M[a][e] + M[d][f] + M[g][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=j;
       I[4]=a; I[5]=e; I[6]=d; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 133: Add c-i h-j a-e d-g f-b for tour AdEbc */
    if (M[c][i] + M[h][j] + M[a][e] + M[d][g] + M[f][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=j;
       I[4]=a; I[5]=e; I[6]=d; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 134: Add c-i h-a j-d e-g f-b for tour AdeBc */
    if (M[c][i] + M[h][a] + M[j][d] + M[e][g] + M[f][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=a;
       I[4]=j; I[5]=d; I[6]=e; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 135: Add c-i h-a j-e d-f g-b for tour AdebC */
    if (M[c][i] + M[h][a] + M[j][e] + M[d][f] + M[g][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=a;
       I[4]=j; I[5]=e; I[6]=d; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 136: Add c-i h-a j-e d-g f-b for tour Adebc */
    if (M[c][i] + M[h][a] + M[j][e] + M[d][g] + M[f][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=a;
       I[4]=j; I[5]=e; I[6]=d; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 137: Add c-h i-a j-f g-d e-b for tour ADeCB */
    if (M[c][h] + M[i][a] + M[j][f] + M[g][d] + M[e][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=a;
       I[4]=j; I[5]=f; I[6]=g; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 138: Add c-h i-a j-f g-e d-b for tour ADeCb */
    if (M[c][h] + M[i][a] + M[j][f] + M[g][e] + M[d][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=a;
       I[4]=j; I[5]=f; I[6]=g; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 139: Add c-h i-a j-g f-d e-b for tour ADecB */
    if (M[c][h] + M[i][a] + M[j][g] + M[f][d] + M[e][b] < r) {
       I[0]=c; I[1]=h; I[2]=i; I[3]=a;
       I[4]=j; I[5]=g; I[6]=f; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 140: Add c-i h-j a-f g-d e-b for tour AdECB */
    if (M[c][i] + M[h][j] + M[a][f] + M[g][d] + M[e][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=j;
       I[4]=a; I[5]=f; I[6]=g; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 141: Add c-i h-j a-f g-e d-b for tour AdECb */
    if (M[c][i] + M[h][j] + M[a][f] + M[g][e] + M[d][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=j;
       I[4]=a; I[5]=f; I[6]=g; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 142: Add c-i h-j a-g f-d e-b for tour AdEcB */
    if (M[c][i] + M[h][j] + M[a][g] + M[f][d] + M[e][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=j;
       I[4]=a; I[5]=g; I[6]=f; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 143: Add c-i h-a j-f g-d e-b for tour AdeCB */
    if (M[c][i] + M[h][a] + M[j][f] + M[g][d] + M[e][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=a;
       I[4]=j; I[5]=f; I[6]=g; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 144: Add c-i h-a j-f g-e d-b for tour AdeCb */
    if (M[c][i] + M[h][a] + M[j][f] + M[g][e] + M[d][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=a;
       I[4]=j; I[5]=f; I[6]=g; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 145: Add c-i h-a j-g f-d e-b for tour AdecB */
    if (M[c][i] + M[h][a] + M[j][g] + M[f][d] + M[e][b] < r) {
       I[0]=c; I[1]=i; I[2]=h; I[3]=a;
       I[4]=j; I[5]=g; I[6]=f; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 146: Add c-j a-f g-i h-d e-b for tour AECdB */
    if (M[c][j] + M[a][f] + M[g][i] + M[h][d] + M[e][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=f;
       I[4]=g; I[5]=i; I[6]=h; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 147: Add c-j a-f g-i h-e d-b for tour AECdb */
    if (M[c][j] + M[a][f] + M[g][i] + M[h][e] + M[d][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=f;
       I[4]=g; I[5]=i; I[6]=h; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 148: Add c-j a-g f-h i-d e-b for tour AEcDB */
    if (M[c][j] + M[a][g] + M[f][h] + M[i][d] + M[e][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=g;
       I[4]=f; I[5]=h; I[6]=i; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 149: Add c-j a-g f-h i-e d-b for tour AEcDb */
    if (M[c][j] + M[a][g] + M[f][h] + M[i][e] + M[d][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=g;
       I[4]=f; I[5]=h; I[6]=i; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 150: Add c-j a-g f-i h-d e-b for tour AEcdB */
    if (M[c][j] + M[a][g] + M[f][i] + M[h][d] + M[e][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=g;
       I[4]=f; I[5]=i; I[6]=h; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 151: Add c-j a-g f-i h-e d-b for tour AEcdb */
    if (M[c][j] + M[a][g] + M[f][i] + M[h][e] + M[d][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=g;
       I[4]=f; I[5]=i; I[6]=h; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 152: Add c-a j-f g-i h-d e-b for tour AeCdB */
    if (M[c][a] + M[j][f] + M[g][i] + M[h][d] + M[e][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=f;
       I[4]=g; I[5]=i; I[6]=h; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 153: Add c-a j-f g-i h-e d-b for tour AeCdb */
    if (M[c][a] + M[j][f] + M[g][i] + M[h][e] + M[d][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=f;
       I[4]=g; I[5]=i; I[6]=h; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 154: Add c-a j-g f-h i-d e-b for tour AecDB */
    if (M[c][a] + M[j][g] + M[f][h] + M[i][d] + M[e][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=g;
       I[4]=f; I[5]=h; I[6]=i; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 155: Add c-a j-g f-h i-e d-b for tour AecDb */
    if (M[c][a] + M[j][g] + M[f][h] + M[i][e] + M[d][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=g;
       I[4]=f; I[5]=h; I[6]=i; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 156: Add c-a j-g f-i h-d e-b for tour AecdB */
    if (M[c][a] + M[j][g] + M[f][i] + M[h][d] + M[e][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=g;
       I[4]=f; I[5]=i; I[6]=h; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 157: Add c-a j-g f-i h-e d-b for tour Aecdb */
    if (M[c][a] + M[j][g] + M[f][i] + M[h][e] + M[d][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=g;
       I[4]=f; I[5]=i; I[6]=h; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 158: Add c-j a-f g-d e-h i-b for tour AECBD */
    if (M[c][j] + M[a][f] + M[g][d] + M[e][h] + M[i][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=f;
       I[4]=g; I[5]=d; I[6]=e; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 159: Add c-j a-f g-d e-i h-b for tour AECBd */
    if (M[c][j] + M[a][f] + M[g][d] + M[e][i] + M[h][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=f;
       I[4]=g; I[5]=d; I[6]=e; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 160: Add c-j a-f g-e d-h i-b for tour AECbD */
    if (M[c][j] + M[a][f] + M[g][e] + M[d][h] + M[i][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=f;
       I[4]=g; I[5]=e; I[6]=d; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 161: Add c-j a-f g-e d-i h-b for tour AECbd */
    if (M[c][j] + M[a][f] + M[g][e] + M[d][i] + M[h][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=f;
       I[4]=g; I[5]=e; I[6]=d; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 162: Add c-j a-g f-d e-h i-b for tour AEcBD */
    if (M[c][j] + M[a][g] + M[f][d] + M[e][h] + M[i][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=g;
       I[4]=f; I[5]=d; I[6]=e; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 163: Add c-j a-g f-d e-i h-b for tour AEcBd */
    if (M[c][j] + M[a][g] + M[f][d] + M[e][i] + M[h][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=g;
       I[4]=f; I[5]=d; I[6]=e; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 164: Add c-a j-f g-d e-h i-b for tour AeCBD */
    if (M[c][a] + M[j][f] + M[g][d] + M[e][h] + M[i][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=f;
       I[4]=g; I[5]=d; I[6]=e; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 165: Add c-a j-f g-d e-i h-b for tour AeCBd */
    if (M[c][a] + M[j][f] + M[g][d] + M[e][i] + M[h][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=f;
       I[4]=g; I[5]=d; I[6]=e; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 166: Add c-a j-f g-e d-h i-b for tour AeCbD */
    if (M[c][a] + M[j][f] + M[g][e] + M[d][h] + M[i][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=f;
       I[4]=g; I[5]=e; I[6]=d; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 167: Add c-a j-f g-e d-i h-b for tour AeCbd */
    if (M[c][a] + M[j][f] + M[g][e] + M[d][i] + M[h][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=f;
       I[4]=g; I[5]=e; I[6]=d; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 168: Add c-a j-g f-d e-h i-b for tour AecBD */
    if (M[c][a] + M[j][g] + M[f][d] + M[e][h] + M[i][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=g;
       I[4]=f; I[5]=d; I[6]=e; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 169: Add c-a j-g f-d e-i h-b for tour AecBd */
    if (M[c][a] + M[j][g] + M[f][d] + M[e][i] + M[h][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=g;
       I[4]=f; I[5]=d; I[6]=e; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 170: Add c-j a-h i-f g-d e-b for tour AEDCB */
    if (M[c][j] + M[a][h] + M[i][f] + M[g][d] + M[e][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=h;
       I[4]=i; I[5]=f; I[6]=g; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 171: Add c-j a-h i-f g-e d-b for tour AEDCb */
    if (M[c][j] + M[a][h] + M[i][f] + M[g][e] + M[d][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=h;
       I[4]=i; I[5]=f; I[6]=g; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 172: Add c-j a-h i-g f-d e-b for tour AEDcB */
    if (M[c][j] + M[a][h] + M[i][g] + M[f][d] + M[e][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=h;
       I[4]=i; I[5]=g; I[6]=f; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 173: Add c-j a-i h-f g-d e-b for tour AEdCB */
    if (M[c][j] + M[a][i] + M[h][f] + M[g][d] + M[e][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=i;
       I[4]=h; I[5]=f; I[6]=g; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 174: Add c-j a-i h-f g-e d-b for tour AEdCb */
    if (M[c][j] + M[a][i] + M[h][f] + M[g][e] + M[d][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=i;
       I[4]=h; I[5]=f; I[6]=g; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 175: Add c-a j-h i-f g-d e-b for tour AeDCB */
    if (M[c][a] + M[j][h] + M[i][f] + M[g][d] + M[e][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=h;
       I[4]=i; I[5]=f; I[6]=g; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 176: Add c-a j-h i-f g-e d-b for tour AeDCb */
    if (M[c][a] + M[j][h] + M[i][f] + M[g][e] + M[d][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=h;
       I[4]=i; I[5]=f; I[6]=g; I[7]=e;
       I[8]=d; I[9]=b;
       return;
    }

    /* Case 177: Add c-a j-h i-g f-d e-b for tour AeDcB */
    if (M[c][a] + M[j][h] + M[i][g] + M[f][d] + M[e][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=h;
       I[4]=i; I[5]=g; I[6]=f; I[7]=d;
       I[8]=e; I[9]=b;
       return;
    }

    /* Case 178: Add c-j a-h i-d e-g f-b for tour AEDBc */
    if (M[c][j] + M[a][h] + M[i][d] + M[e][g] + M[f][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=h;
       I[4]=i; I[5]=d; I[6]=e; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 179: Add c-j a-h i-e d-f g-b for tour AEDbC */
    if (M[c][j] + M[a][h] + M[i][e] + M[d][f] + M[g][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=h;
       I[4]=i; I[5]=e; I[6]=d; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 180: Add c-j a-h i-e d-g f-b for tour AEDbc */
    if (M[c][j] + M[a][h] + M[i][e] + M[d][g] + M[f][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=h;
       I[4]=i; I[5]=e; I[6]=d; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 181: Add c-j a-i h-d e-g f-b for tour AEdBc */
    if (M[c][j] + M[a][i] + M[h][d] + M[e][g] + M[f][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=i;
       I[4]=h; I[5]=d; I[6]=e; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 182: Add c-j a-i h-e d-f g-b for tour AEdbC */
    if (M[c][j] + M[a][i] + M[h][e] + M[d][f] + M[g][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=i;
       I[4]=h; I[5]=e; I[6]=d; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 183: Add c-j a-i h-e d-g f-b for tour AEdbc */
    if (M[c][j] + M[a][i] + M[h][e] + M[d][g] + M[f][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=i;
       I[4]=h; I[5]=e; I[6]=d; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 184: Add c-a j-h i-d e-g f-b for tour AeDBc */
    if (M[c][a] + M[j][h] + M[i][d] + M[e][g] + M[f][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=h;
       I[4]=i; I[5]=d; I[6]=e; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 185: Add c-a j-h i-e d-f g-b for tour AeDbC */
    if (M[c][a] + M[j][h] + M[i][e] + M[d][f] + M[g][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=h;
       I[4]=i; I[5]=e; I[6]=d; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 186: Add c-a j-h i-e d-g f-b for tour AeDbc */
    if (M[c][a] + M[j][h] + M[i][e] + M[d][g] + M[f][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=h;
       I[4]=i; I[5]=e; I[6]=d; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 187: Add c-j a-d e-h i-f g-b for tour AEBDC */
    if (M[c][j] + M[a][d] + M[e][h] + M[i][f] + M[g][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=d;
       I[4]=e; I[5]=h; I[6]=i; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 188: Add c-j a-d e-h i-g f-b for tour AEBDc */
    if (M[c][j] + M[a][d] + M[e][h] + M[i][g] + M[f][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=d;
       I[4]=e; I[5]=h; I[6]=i; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 189: Add c-j a-d e-i h-f g-b for tour AEBdC */
    if (M[c][j] + M[a][d] + M[e][i] + M[h][f] + M[g][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=d;
       I[4]=e; I[5]=i; I[6]=h; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 190: Add c-j a-e d-h i-f g-b for tour AEbDC */
    if (M[c][j] + M[a][e] + M[d][h] + M[i][f] + M[g][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=e;
       I[4]=d; I[5]=h; I[6]=i; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 191: Add c-j a-e d-h i-g f-b for tour AEbDc */
    if (M[c][j] + M[a][e] + M[d][h] + M[i][g] + M[f][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=e;
       I[4]=d; I[5]=h; I[6]=i; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 192: Add c-j a-e d-i h-f g-b for tour AEbdC */
    if (M[c][j] + M[a][e] + M[d][i] + M[h][f] + M[g][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=e;
       I[4]=d; I[5]=i; I[6]=h; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 193: Add c-a j-d e-h i-f g-b for tour AeBDC */
    if (M[c][a] + M[j][d] + M[e][h] + M[i][f] + M[g][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=d;
       I[4]=e; I[5]=h; I[6]=i; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 194: Add c-a j-d e-h i-g f-b for tour AeBDc */
    if (M[c][a] + M[j][d] + M[e][h] + M[i][g] + M[f][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=d;
       I[4]=e; I[5]=h; I[6]=i; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 195: Add c-a j-d e-i h-f g-b for tour AeBdC */
    if (M[c][a] + M[j][d] + M[e][i] + M[h][f] + M[g][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=d;
       I[4]=e; I[5]=i; I[6]=h; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 196: Add c-a j-e d-h i-f g-b for tour AebDC */
    if (M[c][a] + M[j][e] + M[d][h] + M[i][f] + M[g][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=e;
       I[4]=d; I[5]=h; I[6]=i; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 197: Add c-a j-e d-h i-g f-b for tour AebDc */
    if (M[c][a] + M[j][e] + M[d][h] + M[i][g] + M[f][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=e;
       I[4]=d; I[5]=h; I[6]=i; I[7]=g;
       I[8]=f; I[9]=b;
       return;
    }

    /* Case 198: Add c-a j-e d-i h-f g-b for tour AebdC */
    if (M[c][a] + M[j][e] + M[d][i] + M[h][f] + M[g][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=e;
       I[4]=d; I[5]=i; I[6]=h; I[7]=f;
       I[8]=g; I[9]=b;
       return;
    }

    /* Case 199: Add c-j a-d e-g f-h i-b for tour AEBcD */
    if (M[c][j] + M[a][d] + M[e][g] + M[f][h] + M[i][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=d;
       I[4]=e; I[5]=g; I[6]=f; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 200: Add c-j a-d e-g f-i h-b for tour AEBcd */
    if (M[c][j] + M[a][d] + M[e][g] + M[f][i] + M[h][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=d;
       I[4]=e; I[5]=g; I[6]=f; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 201: Add c-j a-e d-f g-i h-b for tour AEbCd */
    if (M[c][j] + M[a][e] + M[d][f] + M[g][i] + M[h][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=e;
       I[4]=d; I[5]=f; I[6]=g; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 202: Add c-j a-e d-g f-h i-b for tour AEbcD */
    if (M[c][j] + M[a][e] + M[d][g] + M[f][h] + M[i][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=e;
       I[4]=d; I[5]=g; I[6]=f; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 203: Add c-j a-e d-g f-i h-b for tour AEbcd */
    if (M[c][j] + M[a][e] + M[d][g] + M[f][i] + M[h][b] < r) {
       I[0]=c; I[1]=j; I[2]=a; I[3]=e;
       I[4]=d; I[5]=g; I[6]=f; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 204: Add c-a j-d e-g f-h i-b for tour AeBcD */
    if (M[c][a] + M[j][d] + M[e][g] + M[f][h] + M[i][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=d;
       I[4]=e; I[5]=g; I[6]=f; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 205: Add c-a j-d e-g f-i h-b for tour AeBcd */
    if (M[c][a] + M[j][d] + M[e][g] + M[f][i] + M[h][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=d;
       I[4]=e; I[5]=g; I[6]=f; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 206: Add c-a j-e d-f g-i h-b for tour AebCd */
    if (M[c][a] + M[j][e] + M[d][f] + M[g][i] + M[h][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=e;
       I[4]=d; I[5]=f; I[6]=g; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    /* Case 207: Add c-a j-e d-g f-h i-b for tour AebcD */
    if (M[c][a] + M[j][e] + M[d][g] + M[f][h] + M[i][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=e;
       I[4]=d; I[5]=g; I[6]=f; I[7]=h;
       I[8]=i; I[9]=b;
       return;
    }

    /* Case 208: Add c-a j-e d-g f-i h-b for tour Aebcd */
    if (M[c][a] + M[j][e] + M[d][g] + M[f][i] + M[h][b] < r) {
       I[0]=c; I[1]=a; I[2]=j; I[3]=e;
       I[4]=d; I[5]=g; I[6]=f; I[7]=i;
       I[8]=h; I[9]=b;
       return;
    }

    *good = 0;
}
